language: python
python: 2.7
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq haskell-platform
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
install: ./scripts/setup
script:
  - ./scripts/cirun --python && ./scripts/cirun --haskell
